name: Push Main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  master:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-22.04
    name: Deploy Static Files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to Cloudflare Pages
        id: cloudflare_deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'file-registry'
          gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
          branch: 'main'
          directory: './files'
          wranglerVersion: '3'

